# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ecf7efcecfe648b51aeb7926b68c1d72cd4df24b8d0ccb0225a9325bf830ee245abfe127dc9c8ace357998e8aace0cf8b13f4e352ff11761d88333088ad1699e
  boot_cage_addr: "0.0.0.0"
  boot_cage_port: 23432

  github_client_id: <%= ENV["GITHUB_CLIENT_ID_DEV"] %>
  github_client_secret: <%= ENV["GITHUB_CLIENT_SECRET_DEV"] %>
  twitter_api_key: <%= ENV["TWITTER_API_KEY_DEV"] %>
  twitter_api_secret: <%= ENV["TWITTER_API_SECRET_DEV"] %>

  devise_secret_key: 'bdeb83ea177023ac30a994c035be1600da26b439cbeddfa08ae57329e618bce1706c7f69e2069a49a0db3ff86fd7c2745a0adc846ac3b48f1d3dc1d22fc2ad7e'
  devise_pepper: 'd6156db4ceaf98b4a6001359e4544aa163f45c769a3f969949d1c0c51d989fa575520e2671702d241a4b69d033db13dd8fc33fa17d4ff0e9d3ba6f79cdbcc2f9'


test:
  secret_key_base: cd31e3914acc84e00ad7a27d3d225b04d38cd775607a63be43316b280c91ddc42dd01a3f25daaa5376dd4a0f28e6d01bf991f5a99dc96cdab084f749f861844c
  boot_cage_addr: "0.0.0.0"
  boot_cage_port: 23432

  github_client_id: <%= ENV["GITHUB_CLIENT_ID_DEV"] %>
  github_client_secret: <%= ENV["GITHUB_CLIENT_SECRET_DEV"] %>
  twitter_api_key: <%= ENV["TWITTER_API_KEY_DEV"] %>
  twitter_api_secret: <%= ENV["TWITTER_API_SECRET_DEV"] %>

  devise_secret_key: 'bdeb83ea177023ac30a994c035be1600da26b439cbeddfa08ae57329e618bce1706c7f69e2069a49a0db3ff86fd7c2745a0adc846ac3b48f1d3dc1d22fc2ad7e'
  devise_pepper: 'd6156db4ceaf98b4a6001359e4544aa163f45c769a3f969949d1c0c51d989fa575520e2671702d241a4b69d033db13dd8fc33fa17d4ff0e9d3ba6f79cdbcc2f9'


# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  boot_cage_addr: <%= ENV["BOOT_CAGE_ADDR"] %>
  boot_cage_port: <%= ENV["BOOT_CAGE_PORT"] %>

  github_client_id: <%= ENV["GITHUB_CLIENT_ID"] %>
  github_client_secret: <%= ENV["GITHUB_CLIENT_SECRET"] %>

  twitter_api_key: <%= ENV["TWITTER_API_KEY"] %>
  twitter_api_secret: <%= ENV["TWITTER_API_SECRET"] %>

  devise_secret_key: <%= ENV["DEVISE_SECRET_KEY"] %>
  devise_pepper: <%= ENV["DEVISE_PEPPER="] %>
